# Generated by Django 4.0.7 on 2024-04-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
